# Generated by Django 4.2.1 on 2023-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
