# Generated by Django 4.2.1 on 2023-08-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_alter_shipping_info_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
    ]
