# Generated by Django 4.2.1 on 2023-08-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_rename_username_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
